runtime: nodejs20 # change to the version of node you are using

instance_class: F2 # Configure your instance class as per your need

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  PORT: 8080

entrypoint: npm start # command to start your server
