version: '3'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres-edumasters
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - .env.development.local
volumes:
  progresDB:
